services:
  alpaca-webui:
    build: .
    container_name: alpaca-webui
    ports:
      - "7860:7860"
    volumes:
      - /home/gabriel/webui_models:/opt/webui/user_data/models:Z
    stdin_open: true
    tty: true
